spring.application.name=pos
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/pos_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:pos_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:pos_password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET:}
jwt.expiration=86400000

CHAPA_SECRET_KEY=${CHAPA_SECRET_KEY:}
chapa.secret-key=${CHAPA_SECRET_KEY:}
chapa.callback-url=${CHAPA_CALLBACK_URL:http://localhost:8080/api/sales/chapa/callback}
chapa.return-url=${CHAPA_RETURN_URL:http://localhost:8080/api/sales/chapa/return}

# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true

# Mail Configuration
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:}
spring.mail.password=${SPRING_MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_STARTTLS:true}